import { NextRequest, NextResponse } from 'next/server';
import { renderToBuffer, Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';
import type { LaunchState } from '@/context/LaunchContext';

export const maxDuration = 60;

const styles = StyleSheet.create({
  page: {
    backgroundColor: '#0a0a0c',
    color: '#e8e8f0',
    fontFamily: 'Courier',
    padding: 40,
    fontSize: 10,
  },
  header: {
    borderBottom: '1px solid #2a2a34',
    paddingBottom: 16,
    marginBottom: 24,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  headerLeft: {},
  projectName: {
    fontSize: 16,
    color: '#c084fc',
    fontFamily: 'Courier-Bold',
    marginBottom: 4,
  },
  headerDate: {
    fontSize: 8,
    color: '#60607a',
  },
  rocketText: {
    fontSize: 18,
    color: '#7F77DD',
  },
  section: {
    marginBottom: 20,
    borderLeft: '2px solid #3a3a48',
    paddingLeft: 12,
  },
  sectionTitle: {
    fontSize: 9,
    color: '#9090a8',
    letterSpacing: 2,
    marginBottom: 10,
    fontFamily: 'Courier-Bold',
  },
  item: {
    fontSize: 10,
    color: '#9090a8',
    marginBottom: 6,
    flexDirection: 'row',
    gap: 8,
  },
  arrow: {
    color: '#7F77DD',
    width: 12,
  },
  compCard: {
    backgroundColor: '#13131a',
    padding: 10,
    marginBottom: 8,
    borderLeft: '3px solid #2a2a34',
  },
  compName: {
    fontSize: 11,
    color: '#e8e8f0',
    fontFamily: 'Courier-Bold',
    marginBottom: 4,
  },
  compDesc: {
    fontSize: 9,
    color: '#9090a8',
    marginBottom: 4,
  },
  compWeakness: {
    fontSize: 9,
    color: '#9090a8',
    borderTop: '1px dashed #3a3a48',
    paddingTop: 4,
  },
  angleBox: {
    border: '1px dashed #7F77DD',
    padding: 12,
    marginBottom: 16,
    backgroundColor: '#0d0d14',
  },
  angleLabel: {
    fontSize: 8,
    color: '#7F77DD',
    marginBottom: 6,
  },
  angleText: {
    fontSize: 11,
    color: '#c084fc',
  },
  channelRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    padding: 10,
    backgroundColor: '#13131a',
    marginBottom: 6,
    borderLeft: '3px solid #2a2a34',
  },
  channelRowPrimary: {
    borderLeft: '3px solid #c084fc',
  },
  channelIcon: {
    width: 36,
    height: 36,
    border: '1px dashed #3a3a48',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 13,
    color: '#9090a8',
    flexShrink: 0,
  },
  channelName: {
    fontSize: 12,
    color: '#e8e8f0',
    fontFamily: 'Courier-Bold',
    marginBottom: 3,
  },
  channelWhy: {
    fontSize: 9,
    color: '#9090a8',
  },
  contentSection: {
    backgroundColor: '#13131a',
    padding: 12,
    marginBottom: 8,
    border: '1px dashed #3a3a48',
  },
  contentLabel: {
    fontSize: 8,
    color: '#7F77DD',
    marginBottom: 6,
    fontFamily: 'Courier-Bold',
  },
  contentText: {
    fontSize: 9,
    color: '#9090a8',
    lineHeight: 1.6,
  },
  footer: {
    position: 'absolute',
    bottom: 20,
    left: 40,
    right: 40,
    borderTop: '1px dashed #3a3a48',
    paddingTop: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  footerText: {
    fontSize: 8,
    color: '#60607a',
  },
});

export async function POST(req: NextRequest) {
  try {
    const body = await req.json() as { fullStrategy: LaunchState };
    const { fullStrategy } = body;

    const {
      repoName,
      competitors,
      positioningAngle,
      demographics,
      channels,
      githubTips,
      opportunityNote,
      content,
      positioningStatement,
      tagline,
    } = fullStrategy;

    const selectedDemos = demographics.filter(d => d.selected).map(d => d.label);
    const now = new Date();
    const dateStr = now.toLocaleDateString('en-US', { month: 'long', year: 'numeric' }).toLowerCase();

    const doc = (
      <Document>
        <Page size="A4" style={styles.page}>
          {/* Header */}
          <View style={styles.header}>
            <View style={styles.headerLeft}>
              <Text style={styles.projectName}>{repoName || 'your_project'} — launch_strategy.pdf</Text>
              <Text style={styles.headerDate}>// generated by launchpad_ai · {dateStr}</Text>
            </View>
            <Text style={styles.rocketText}>[LP]</Text>
          </View>

          {/* Positioning */}
          {positioningAngle && (
            <View style={styles.angleBox}>
              <Text style={styles.angleLabel}>// your angle</Text>
              <Text style={styles.angleText}>{positioningAngle}</Text>
            </View>
          )}

          {/* Tagline */}
          {tagline && (
            <View style={{ marginBottom: 16 }}>
              <Text style={{ fontSize: 8, color: '#9090a8', marginBottom: 4 }}>// tagline</Text>
              <Text style={{ fontSize: 13, color: '#c084fc', fontFamily: 'Courier-Bold' }}>{tagline}</Text>
            </View>
          )}

          {/* Positioning statement */}
          {positioningStatement && (
            <View style={{ marginBottom: 20, padding: 10, border: '1px dashed #2a2a34' }}>
              <Text style={{ fontSize: 8, color: '#9090a8', marginBottom: 6 }}>// positioning statement</Text>
              <Text style={{ fontSize: 10, color: '#e8e8f0', lineHeight: 1.6 }}>{positioningStatement}</Text>
            </View>
          )}

          {/* Competitors */}
          {competitors.length > 0 && (
            <View style={styles.section}>
              <Text style={styles.sectionTitle}>// competitive landscape</Text>
              {competitors.map((comp, i) => (
                <View key={i} style={styles.compCard}>
                  <Text style={styles.compName}>{comp.name}</Text>
                  <Text style={styles.compDesc}>{comp.description}</Text>
                  <Text style={styles.compWeakness}>weakness: {comp.weakness}</Text>
                </View>
              ))}
            </View>
          )}

          {/* Audience */}
          {selectedDemos.length > 0 && (
            <View style={styles.section}>
              <Text style={styles.sectionTitle}>// target audience</Text>
              {selectedDemos.map((d, i) => (
                <View key={i} style={styles.item}>
                  <Text style={styles.arrow}>→</Text>
                  <Text style={{ color: '#5DCAA5', fontSize: 10 }}>{d}</Text>
                </View>
              ))}
            </View>
          )}

          {/* Channels */}
          {channels.length > 0 && (
            <View style={styles.section}>
              <Text style={styles.sectionTitle}>// launch channels</Text>
              {channels
                .sort((a, b) => a.priority - b.priority)
                .map((ch, i) => (
                  <View key={i} style={[styles.channelRow, ch.isPrimary ? styles.channelRowPrimary : {}]}>
                    <View style={styles.channelIcon}>
                      <Text>{ch.icon}</Text>
                    </View>
                    <View style={{ flex: 1 }}>
                      <Text style={styles.channelName}>{ch.name}</Text>
                      <Text style={styles.channelWhy}>{ch.why}</Text>
                    </View>
                    <Text style={{ fontSize: 9, color: '#c084fc' }}>#{ch.priority}</Text>
                  </View>
                ))}
            </View>
          )}

          {/* GitHub Tips */}
          {githubTips.length > 0 && (
            <View style={styles.section}>
              <Text style={styles.sectionTitle}>// github moves</Text>
              {githubTips.map((tip, i) => (
                <View key={i} style={styles.item}>
                  <Text style={styles.arrow}>→ 0{i + 1}</Text>
                  <Text style={{ color: '#9090a8', flex: 1 }}>{tip}</Text>
                </View>
              ))}
            </View>
          )}

          {/* Opportunity */}
          {opportunityNote && (
            <View style={{ backgroundColor: '#1a1200', border: '1px solid #854F0B', padding: 12, marginBottom: 16 }}>
              <Text style={{ fontSize: 8, color: '#EF9F27', marginBottom: 6 }}>// opportunity</Text>
              <Text style={{ fontSize: 10, color: '#EF9F27', lineHeight: 1.6 }}>{opportunityNote}</Text>
            </View>
          )}

          {/* Content Snippets */}
          {(content.twitter || content.reddit) && (
            <View style={styles.section}>
              <Text style={styles.sectionTitle}>// content snippets</Text>
              {content.twitter && (
                <View style={styles.contentSection}>
                  <Text style={styles.contentLabel}>// twitter</Text>
                  <Text style={styles.contentText}>{content.twitter.slice(0, 300)}{content.twitter.length > 300 ? '...' : ''}</Text>
                </View>
              )}
              {content.reddit && (
                <View style={styles.contentSection}>
                  <Text style={styles.contentLabel}>// reddit</Text>
                  <Text style={styles.contentText}>{content.reddit.slice(0, 300)}{content.reddit.length > 300 ? '...' : ''}</Text>
                </View>
              )}
            </View>
          )}

          {/* Footer */}
          <View style={styles.footer} fixed>
            <Text style={styles.footerText}>// launchpad_ai · launch_strategy.pdf</Text>
            <Text style={styles.footerText}>{dateStr}</Text>
          </View>
        </Page>
      </Document>
    );

    const buffer = await renderToBuffer(doc);
    const uint8 = new Uint8Array(buffer);

    return new NextResponse(uint8, {
      status: 200,
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="${repoName || 'launchpad'}_strategy.pdf"`,
      },
    });
  } catch (err) {
    const message = err instanceof Error ? err.message : 'Unknown error';
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
